### ISSUE TITLE
argument parsing sometimes fails when providing portmask

### ISSUE THREAD

**Issue by craiggarrett** [dpdkcap/dpdkcap#12]
When I include the -p option, sometimes an error is generated by the `parse_opt(int key, char* arg, struct argp_state *state)` function in dpdkcap.c. I think this has to do with the global variable errno being a non-zero value before line 81: `arguments->portmask = strtoul(arg, &end, 16);` and the strtoul function is not required to set errno to 0 on success. So even if the call to strtoul is successful, errno can still be a non-zero value afterwards, causing the conditional on line 82/83 to think there is an error condition. Therefore, I recommend setting errno to 0 right before the call to strtoul.

Recommendation: insert this line before line 81 in dpdkcap.c (on develop branch):
`errno = 0; // reset errno because it is not set to 0 by strtoul on success`

**Comment by groud** [comment]
Yep, you are right.
I will fix this.

**Comment by groud** [comment]
Done :)

**Comment by craiggarrett** [comment]
Thanks!
