### ISSUE TITLE
Possible overflows of packet and byte counters for large amounts of data

### ISSUE THREAD

**Issue by craiggarrett** [dpdkcap/dpdkcap#13]
In several places in the code, 32-bit `long` or `unsigned long` is used to keep track of packet or byte counts. For high-speed networks, it's easy to get more than 2G/4G of bytes or even packets. I'd recommend changing the types of these variables to uint64_t (this type is used in the struct rte_eth_stats provided by DPDK and used by statistics_ncurses.c).

Here are a few of these variables that I noticed (but this may not be all of them):

**statistics_ncurses.c:**
function wwrite_stats():
`static long last_total_packets = 0,
		  last_total_bytes = 0,
		  last_total_compressedbytes = 0;
long total_packets = 0,
   total_bytes = 0,
   total_compressedbytes = 0;
long instant_packets,
   instant_bytes,
   instant_compressedbytes;`
function wcapture_stats()
`static unsigned long * last_per_port_packets = NULL;`

**core_capture.h**
`struct core_capture_stats 
  unsigned long packets; //Packets successfully enqueued
  unsigned long missed_packets; //Packets core could not enqueue`
  
**core_write.h**
`struct core_write_config
unsigned long file_size_limit;`
`struct core_write_stats
  unsigned long current_file_packets;
  unsigned long current_file_bytes;
  unsigned long current_file_compressed_bytes;
  unsigned long packets;
  unsigned long bytes;
  unsigned long compressed_bytes;`

**dpdkcap.c**
`struct arguments
unsigned int file_size_limit;`

(sorry for the poor formatting!)

Oh, and if you make this change, don't forget to change the malloc size in statistics_ncurses.c line 35:
`malloc(sizeof(unsigned long) * data->cores_capture_stats_list_size)`
should be 
`malloc(sizeof(uint64_t) * data->cores_capture_stats_list_size)`

**Comment by groud** [comment]
Ok, I changed all those variables types in the files. I think none is missing. :ok_hand: 

Btw, the next time you do such hard work, do not hesitate to fork, modify the code and do a pull request. :) Anyway thanks again !
