### ISSUE TITLE
wire rate performance?

### ISSUE THREAD

**Issue by fastxs** [dpdkcap/dpdkcap#14]
Not sure if something is not correct but capturing about 800K pps (average 400-500 bytes) will need 16 cores even that packet is missing - is there a rule of thumb how many cores you need for average packet capture and writing?

**Comment by groud** [comment]
Well, this problem is quite complicated.
Usually a single capture core is needed, while a lot more are needed for writting, due to compression.
The bad performances might be due to a lot a thing (disk I/O, too many capturing corecausing memory access jam, too low writing core... ).
The only advise I could giveis not to use more than one capture core, adding more did lower the performances in my situation : In my experiments I needed 1 capture core, 1 main core, and 15 cores to capture a 10Gb/s traffic.

**Comment by fastxs** [comment]
in trying the no-compression version single core would stop capturing about 1 million packets (and 2 core would stop 2 million)  with (8 writing core) then give errors like "MBUF Allocation failures" RX-error but the original version seems continue as long as disk is allowed

**Comment by groud** [comment]
I do not understand very well what you are saying.
I mean, DPDKCap should not stop capturing in any situation. But at a given point, you may be limited by either your number of wrtting cores  or your disk bandwidth.

**Comment by craiggarrett** [comment]
Can you try creating a ramdisk (tmpfs) and having dpdkcap write to the ramdisk? If it is able to write at high speeds to the ramdisk with no problems, then you know you are disk (IO) limited when you are writing to a normal disk.

**Comment by fastxs** [comment]
thank you yes using tmpfs can almost achieving wire rate without dropping ( write 5.5m pps average)

**Comment by groud** [comment]
Awesome :)
If you are limited by your hard drive(s) bandwidth, remember to keep the lzo compression. This is a computationally cheap algorithm, and it can divide by 4 the I/O needed. This being said, @Woutifier might have more to say about that, as he have been using LZO since the first version of DPDKCap ;)

**Comment by Woutifier** [comment]
I was able to achieve 10 Gbit/s wire rate (i.e. 16.7m 64-byte packets per second) using a few cores (the exact number escapes me), however, that was using easily compressible packets. I agree with @groud that you are likely limited by IO (the reason why I built in LZO in the first place :-)).

Depending on how much your packets can be compressed the rate that you can achieve may be vary. For example: A bunch of video streams will be less likely to compress well than a bunch of text. This also means that the rate that you can achieve is likely to change over time as the content of the packets changes.

**Comment by fastxs** [comment]
thanks yes looks like the disk IO is the problem

**Comment by groud** [comment]
Ok.
To fix the problem, I used a RAID0 to allow a faster I/O. As I used multiple hard drive (6) I could achieve good results. I also used _iotop_ for monitoring I/O.

**Comment by fastxs** [comment]
thank you
Also have you compared with native dpdk-pdump performance ?

**Comment by groud** [comment]
What do you mean ? Like the pktgen app ?
I don't know what is dpdk-pdump :/

**Comment by fastxs** [comment]
yes it is a sample app comes with dpdk

**Comment by groud** [comment]
Ah yes, I did not even know it actually existed. Thus I obviously did not tested it :)
Anyway, it seems like it does not perform compression, so I guess it cannot achieve as good performances than our tool.

However, I see interesting features in the code, such as the ability to use a virtual device as a target output. It might be interesting :)

**Comment by craiggarrett** [comment]
I saw that library and the pdump app a couple of months ago, but I didn't think it was appropriate for high-performance as it requires memory transfer to a secondary process. This article from Intel says [the librte_pdump library works on a client/server model and its usage is recommended for debugging purposes.](https://software.intel.com/en-us/articles/dpdk-packet-capture-framework)

That said, I haven't tried it to see how fast it is.

**Comment by fastxs** [comment]
yes also not all the nic would work with primary/secondary model

**Comment by fastxs** [comment]
which parameter is the cause of "MBUF Allocation Failures" -

**Comment by groud** [comment]
Have you pulled the last dpdkcap version ?
In the last version, the number of mbuf used for each port is fixed depending on your port capabilities. Those problems should not happen anymore.

If this still happen in the last version, please send the logs you get.

**Comment by craiggarrett** [comment]
Which commit was that in? I'm interested for another dpdk project, so I'd love to see the exact code change you made to do this.

**Comment by groud** [comment]
Ah ok :)
The commit is this one 9345d8333bfefc6999fb48acb5f4c7733aab007e
The new code retrieves the maximum rx_descriptors usable and use it for the queue setup.

**Comment by craiggarrett** [comment]
Very interesting - thank you!

**Comment by fastxs** [comment]
the latest version has this error:

DPDKCAP: rte_eth_rx_queue_setup(...) returned with error code -12EAL: Error - exiting with code: 1  Cause: Cannot init port 0

**Comment by groud** [comment]
Have a look to the documentation: http://dpdk.org/doc/api/rte__ethdev_8h.html#a8db38c1bb895250a99b217bb24126d8e.

It says it was not able to allocate the receive ring descriptors or to allocate network memory buffers from the memory pool when initializing receive descriptors. Are you sure you have enough memory left ?

**Comment by fastxs** [comment]
yes the machine has 96gb and  can run the other version of dpdkcap fine. when comparing the files  notice changes - in reading errors,  was thinking does the changes you put on latest version works on non-intel nic?
PMD: mlx5_rxq.c:1231: mlx5_rx_queue_setup(): 0x918a00: increased number of descriptors in RX queue 0 to the next power of two (0)
PMD: mlx5_rxq.c:1031: rxq_ctrl_setup(): 0x918a00: CQ creation failure: Cannot allocate memory
these 2 lines did not show up in the working version

**Comment by groud** [comment]
Those two lines are the logs you get ?
```
PMD: mlx5_rxq.c:1231: mlx5_rx_queue_setup(): 0x918a00: increased number of descriptors in RX queue 0 to the next power of two (0) 
PMD: mlx5_rxq.c:1031: rxq_ctrl_setup(): 0x918a00: CQ creation failure: Cannot allocate memory these 2 lines did not show up in the working version
```
The problem might come from the fact that the number of RX queue descriptors is increased to the next power of 2. I don't know why this happens, as I fix this number to the max available using `rte_eth_dev_info_get`, maybe it is not aligned to a power of 2...

Could you show me the command you use to run dpdkcap ? I might have an idea about where it come from.

**Comment by fastxs** [comment]
same command (latest version and previous working version): build/dpdkcap -c 0x7e007f -- -w 4 -c 1 -S  -s 72 --no-compression
2 mlx5 10Gbunch of intel 1G (but not using them for dpdk)

**Comment by craiggarrett** [comment]
I'm also getting an error, and dpdkcap used to work with older versions. Not sure if this is related to the issue that fastxs is having because my output is different. If you think it's a different issue and would like me to submit a new issue for it, let me know.

Here's my command line and output:
Command Line:
`sudo -E ./build/dpdkcap --master-lcore 0 -w 00:08.0 -c 0xf -n 1 -- --limit_file_size=250000000 -p 0x1 -c 1 -w 1`

Output:
```
EAL: Detected 4 lcore(s)
EAL: Probing VFIO support...
EAL: PCI device 0000:00:08.0 on NUMA socket -1
EAL:   probe driver: 8086:100e net_e1000_em
DPDKCAP: Using 1 ports to listen on
DPDKCAP: Using 3 cores out of 4 allocated
PMD: eth_em_rx_queue_setup(): sw_ring=0x7f86dea23180 hw_ring=0x7f86dea2b280 dma_addr=0x8d62b280
DPDKCAP: rte_eth_dev_set_rx_queue_stats_mapping(...) returned with error code -95
DPDKCAP: The queues statistics mapping failed. The displayed queue statistics are thus unreliable.
DPDKCAP: Core 1 is writing using file template: output_%COREID_%FCOUNT.pcap.lzo.
PMD: eth_em_tx_queue_setup(): sw_ring=0x7f86dea12e40 hw_ring=0x7f86dea13140 dma_addr=0x8d613140
DPDKCAP: Port 0 MAC: 08 00 27 29 cd 14
DPDKCAP: Core 2 is capturing packets for port 0
PMD: em_alloc_rx_queue_mbufs(): RX mbuf alloc failed queue_id=0
PMD: eth_em_start(): Unable to initialize RX hardware
EAL: Error - exiting with code: 1
  Cause: Cannot start port 0
```

  
I went through the commits, trying each one until I found that commit that introduced the issue: 
`Commit: 9345d8333bfefc6999fb48acb5f4c7733aab007e`
`Comment: Set the number of used rx/tx descriptors to the max/min (according to the port capabilities)`

The previous commit to that one works: `b34a59e67779662a6db425327b49cf0e1daf6186`

**Comment by groud** [comment]
Yep, I am not really confident about this, but this might come from the fact that the `dev_inf.rx_desc_lim.nb_max` value is not the max number or rx desc for each queue, but for all queues.
Sadly, this is not well documented... :/

As I use a NIC with only one queue allowed the value seemed ok in my situation.

**Comment by craiggarrett** [comment]
That could be, but there might be another issue because I was only asking for 1 rx queue (i.e. 1 capture core)

**Comment by groud** [comment]
According to fastxs logs, it seems that DPDK automatically raises **up** the number of required rx descriptors to the upper power of 2. So even if you are requesting only one queue, if `dev_inf.rx_desc_lim.nb_max` is not aligned to a power of 2, the requested number go too high (and cause failure).

**Comment by fastxs** [comment]
so should we go back the previous working version

**Comment by groud** [comment]
I might have the time to fix the problem this week end.
You can use the commit previous to the problematic one for the moment.

**Comment by groud** [comment]
I asked a question about this problem in a DPDK mailist. If i've got an answer I'll be able to fix this fast.

**Comment by fastxs** [comment]
thanks!

**Comment by groud** [comment]
I might have fixed the problem, but I did not have any answer from the mailing list yet.
The actual code considers that dev_info.rx_desc_lim.nb_max is the maximum number of RX descriptors for the whole set of queues. 
I cannot test if this code works (virtual interfaces do not care about the number of rx_desc), so if one of you could test this on his configuration that would be great :)

**Comment by fastxs** [comment]
yes i will test - git out the dev branch?

**Comment by groud** [comment]
Yes,` git pull origin develop` then `git checkout develop` :)

**Comment by fastxs** [comment]
- Compiled and run got this error:DPDKCAP: rte_eth_rx_queue_setup(...): Cannot allocate memoryEAL: Error - exiting with code: 1  Cause: Cannot init port 0
- changed NUM_MBUFS to 65536 then no error BUT it will only write 1 packet and nothing moving:

**Comment by groud** [comment]
Oh, I just figured out what could be the problem.
The errors must come from the fact that the MBUF pool might not be large enough to handle the number of descriptors required... :/ So by increasing the number of MBUFS the problem could have been fixed.

Could you try to checkout the last but one commit, and try to increase the number of MBUFs, then see if it works ?

**Comment by fastxs** [comment]
apologize but don't know how to " checkout the last but one commit,"? (I checked out the dev by -b develop)

**Comment by groud** [comment]
Yes, you are right for the `-b`.
Use `git checkout HEAD^` to checkout the last but one commit.

**Comment by craiggarrett** [comment]
I had to reduce nb_desc by another power of two (or rather, reduce it by a power of two even if it was already a power of two):

`nb_desc = dev_info.rx_desc_lim.nb_max / rx_rings;`
`nb_desc = rte_align32pow2(nb_desc) / 2;`

(notice the if statement checking if it was already a power of two is gone).

Also, I've been running with NUM_MBUFS equal to 65535 or higher, and my card is a Mellanox ConnectX-4, and it reports 65535 for `dev_info.rx_desc_lim.nb_max`

Related to all this, there may be a bug of some kind in the dpdk or net_mlnx5 libraries (I'm using dpdk-17.02-rc1) because if I run with 1 queue, and pass in 65535 to rte_eth_rx_queue_setup(), then I get this error message:

`PMD: net_mlnx5: 0x8bffc0: increased number of descriptors in RX queue 0 to the next power of two (0)`

Obviously (0) is not a power of two, so that may be a DPDK or net_mlnx5 bug.

**Comment by groud** [comment]
Actually I have also a problem with rte_eth_rx_queue_setup(). Even if I use a very high number of descriptors, it does not throw any error. This is why it is difficult for me to run tests. :/

I don't really know how to deal with this problem. I might have a strategy, which would be the following:
- I fix a default number of MBUF (to a power of 2 minus one, as suggested in the documentation), that can be modified by the user.
- The number of entries in the write ring if fixed to the next power of 2,
- Then I configure all queues to `dev_inf.rx_desc_lim.nb_max` if possible. 

If not, maybe we can find several solutions:
- Fix all number of RX desc to the minimum (and maybe display a warning)
- Reduce this number until it fits the MBUF pool size
- Or, more complicated, use a complex argument parsing to let the user configure for each port the number of RX descriptors per queue

**Comment by craiggarrett** [comment]
I agree that MBUF should be a command line parameter, and perhaps RX desc per queue should be as well. This would give the user the ability to adjust things if needed. 

Otherwise, yes, reducing RX desc per queue by a power of 2 until the call to rte_eth_rx_queue_setup() returns successfully is another strategy.

**Comment by craiggarrett** [comment]
I don't know if this is related, but according to this page: [http://dpdk.org/doc/api/rte__ethdev_8h.html](http://dpdk.org/doc/api/rte__ethdev_8h.html)

The functions exported by the application Ethernet API to setup a device designated by its port identifier must be invoked in the following order:

- rte_eth_dev_configure()
- rte_eth_tx_queue_setup()
- rte_eth_rx_queue_setup()
- rte_eth_dev_start()

But in the dpdkcap.c: port_init() function, rte_eth_rx_queue_setup() is called before rte_eth_tx_queue_setup()

**Comment by groud** [comment]
Well I dont think this does affect the proper functionning of the software, but yes, this could be modifyed just in case.

**Comment by fastxs** [comment]
checkout HEAD^ would produce the same error

**Comment by groud** [comment]
Ok well, I think we have no other solution by now to revert to a more simple approch.
I will fix the nulber of MBUF to a higher value, and force the nb of rx descriptor to the minimum value.

This should fix the problem until we have more controls on these values with arguments.

**Comment by groud** [comment]
The nb_mbuf argument is now added in the last version of the develop branch.

**Comment by groud** [comment]
@fastxs I close the issue for now, if you have more questions feel free to ask. :)

**Comment by fastxs** [comment]
the option "-s" packet length - is it possible to say packet header (meta data) only?

**Comment by groud** [comment]
Well, if you choose something like 64 bytes, you will get all headers from the MAC, IP and UDP/TCP header, and maybe a part of the payload.
Anyway, this is a fixed value, you cannot use a dynamically chosen value with the -s option.
