### ISSUE TITLE
Statistics not refreshing/calculating on the correct time interval

### ISSUE THREAD

**Issue by craiggarrett** [dpdkcap/dpdkcap#16]
I was noticing that the live/instant statistics were off for me by a reliable amount (10% on a bare metal machine, and 25% on a virtual machine), and I think I've discovered why. When the timer is setup in statistics_ncurses.c, on line 257/258, the "ticks" value passed to rte_timer_reset() assumes a frequency of 2000000ULL (in thousands of ticks), but this is not always the correct value for every computer. Recommend using rte_get_timer_hz() in rte_cycles.h to calculate the correct number of ticks:

In statistics_ncurses.c, add:
`#include <rte_cycles.h>`
in the start_stats_display() function:
`uint64_t ticks = rte_get_timer_hz() * STATS_PERIOD_MS / 1000;`
`rte_timer_reset(&(stats_timer), ticks, PERIODICAL, lcore_id, (void*) printscreen, data);`

**Comment by groud** [comment]
This seems ok to me. :)

**Comment by groud** [comment]
Fixed !
Thanks again :)

**Comment by craiggarrett** [comment]
Awesome - looks good! Thanks!
