### ISSUE TITLE
Packet filtering

### ISSUE THREAD

**Issue by craiggarrett** [dpdkcap/dpdkcap#17]
It would be very powerful if we could filter the packets that are saved to disk, similar to how tcpdump can filter packets with Berkeley Packet Filters, including filtering based on Port, MAC, VLAN, src/dst IP address/subnet, IP Protocol (TCP/UDP/ICMP/etc.) and TCP/UDP src/dst Port. Packets matching the filter would be saved to disk; all packets that did not match the filter would be discarded.

This may be tough to implement, so this feature request thread may be more of a place for us to discuss how this might be implemented. However, there may be some features within the DPDK API that already support this to some extent, but I haven't found them yet. 

There is a long thread discussing this at dpdk.org in December 2015, but there was no resolution to it:
[Thread list: [dpdk-dev] tcpdump support in DPDK 2.3](http://dpdk.org/ml/archives/dev/2015-December/thread.html#30442)
[Parent message: [dpdk-dev] tcpdump support in DPDK 2.3](http://dpdk.org/ml/archives/dev/2015-December/030174.html)

Your thoughts?

**Comment by groud** [comment]
That would be an awesome. However, you are right, this is quite complicated to implement
But I agree to start a thread about that:
- TCPDump (and thus libpcap) use the BPF syntax to define the filter. This might be a good idea to implement this filter.
- Maybe we can take a little bit of code from the libpcap library, we have to check its license and the compatibility with ours.
Edit:
- From what I see, BPF is more than a language. The given entries are compiler into a special bytecode, than is usually handled by the kernel. I do not know if we can find a way to adapt it to DPDK.

**Comment by craiggarrett** [comment]
> given entries are compiler into a special bytecode, than is usually handled by the kernel

That's correct, and you're right that makes it more complicated (impossible?) to use BPF in user-space. I'm probably going to look into that in the next couple of weeks, and see what's possible. I'll let you know if I find anything interesting.

There may be other approaches, such as using ethtool for splitting the traffic that comes to DPDK. I'll try to look into that too.

**Comment by groud** [comment]
It seems that within DPDK, the flow API is here to handle hardware packet filters:
http://dpdk.org/doc/api/rte__flow_8h.html
and here:
http://dpdk.org/doc/guides/prog_guide/rte_flow.html

**Comment by craiggarrett** [comment]
Yes, it looks like rte_flow was added in DPDK 17, which is still in release candidate status, but it looks very promising. I'll try it out.

[Download of all versions, including 17.02-rc1](http://dpdk.org/browse/dpdk/refs/)

**Comment by craiggarrett** [comment]
I found that BPF does have an offline mode, where it can check an individual packet (a char* with a pcap packet header) against the filter. I'll try to post some example code soon. I don't know how good the performance will be, though. It may depend on the complexity of the filter, but we'd have to try it to know for sure.

**Comment by groud** [comment]
Well, if it has to copy the packet into the kernel space, this might end up in noticeable performances losses. I am not sure if that combining DPDK with kernel dependant API should be done. :/
Anyway, if this is the only way we can do that, it's better than nothing :)

**Comment by craiggarrett** [comment]
I agree, if the filter is done in kernel space, that could cause a performance problem. According to the tcpdump manpage, it *should* happen in user space, but it doesn't say that specifically:

["For a live capture, the filtering will be performed in kernel mode, if possible"](http://www.tcpdump.org/manpages/pcap.3pcap.html#lbAH)

**Comment by craiggarrett** [comment]
From what I can tell, offline mode BPF filtering happens in user space. Normally when people use libpcap in online mode, they call `pcap_setfilter(pcap_t *p, struct bpf_program *fp)` which results in a kernel call to `setsockopt()` with the option `SO_ATTACH_FILTER`. This results in the kernel placing the BPF program on the socket, so the kernel can apply the filter to each packet as it comes in, before the packet is sent to user space. 

In offline mode, however, there don't seem to be any kernel calls related to the BPF at all. The data and calls also don't go through any socket. (I used `strace` on tcpdump and on dpdkcap+test BFP code and compared the output). And looking through the code in libpcap, the call stack looks like this:

`pcap_offline_filter(bpf_program *fp, pcap_pkthdr *h, u_char *pkt)` ->
---`bpf_filter(fcode, pkt, h->len, h->caplen)` ->
------`bpf_filter_with_aux_data(pc, pkt, wirelen, buflen, NULL)`

The `bpf_filter_with_aux_data()` function runs the BPF program against the packet, and doesn't make any memory copies or calls to kernel space.

I'll keep looking and testing, and I'll let you know what else I find out. I'll post some sample code as well.

**Comment by fastxs** [comment]
this will be a powerful feature - you mentioned you have sample code test BFP, is it in the dev branch already?

**Comment by Woutifier** [comment]
It seems to me that this should be possible. Although there is no code in the dev branch as of yet.

A few notes:
The syntax that tcpdump uses (e.g. "tcp and port 80") is not BPF, it just compiles to it. Using the command tcpdump -ddd "tcp and port 80" you can obtain the bytecode (use only one d to have a more human-readable format). 

Once you have the BPF bytecode (e.g. for the previous example: 20,40 0 0 12,21 0 6 34525,48 0 0 20,21 0 15 6,40 0 0 54,21 12 0 80,40 0 0 56,21 10 11 80,21 0 10 2048,48 0 0 23,21 0 8 6,40 0 0 20,69 6 0 8191,177 0 0 14,72 0 0 14,21 2 0 80,72 0 0 16,21 0 1 80,6 0 0 262144,6 0 0 0), you either need a kind of virtual machine that understands this bytecode or you need a JIT compiler that compiles the bytecode to x86. You won't have to move stuff to kernel space or whatever, we can probably use parts of their code (if the licenses are compatible?).

I am not entirely sure how much work it would be to implement this although it is very interesting to see how this works.

**Comment by fastxs** [comment]
I see tcpdump (a) compile the filter and (b) set the filter - do you need both to be operated at kernel hence you waste 2 cycle for each processing? My question is performance as DPDK is trying to beat the performance race

**Comment by craiggarrett** [comment]
I haven't put the code in the development branch yet, but hopefully I will be able to do that soon. My preliminary testing shows that the libpcap-based BPF calls are very fast and should be able to handle very high packet rates (several million packets per second), depending on the complexity of the specific filter used and how many CPU cores you have.

**Comment by fastxs** [comment]
will be curious to test.when you put on dev
the latest version I can use only 4 core to write and 1 core capture with 14.5mpps almost wire rate so I think adding another few cores to this function is reasonable

**Comment by fastxs** [comment]
Can "-s" be dynamic? If "field=value" then "-s 100" - looks at the PCAP definition this seems possible since each packet there is a definition of snaplength

**Comment by groud** [comment]
Well, the pcap format allows that but I am not sure this is really useful
considering the work this would need.
Once we will have the filtrer feature,  this might be to consider, but not
right now.

**Comment by xaki23** [comment]
packet filtering is implemented as of https://github.com/dpdkcap/dpdkcap/commit/376f409cea3b700b6b74be0381f3d29e89e60a24
this uses the dpdk native BPF support: https://doc.dpdk.org/api/rte__bpf_8h.html

first libpcap is used to compile the user-supplied filter string to a pcap-bpf program, then converts the pcap-bpf to rte-bpf.
the writer core then applies the rte-bpf "program" to the packet bursts to decide which ones to write to file.
with the taskdir feature, this also means you can run multiple bpf filters, directing matched packets to different files, and can add/remove filters without restarting dpdkcap.

running multiple filters is more efficient than i expected it to be, like the first filter causes 20% cpu load on the writer core, but then each additional one only adds another 10% cpu load. 
without having investigated closer, i assume this is because the first filter loads the packets/headers to cpu cache, and the additional filters run on that cached packet data. 

unless the "dynamic snaplen" part is considered essential, this issue can probably be closed for now.

**Comment by groud** [comment]
Alright, since BPF is not implemented, I'll close this issue. If anyone has a more specific need, they are welcome to open a new issue.
