### ISSUE TITLE
Cannot init port 0

### ISSUE THREAD

**Issue by diegodem** [dpdkcap/dpdkcap#2]
After following the entire README, when I try to launch the program I get the following:

$ sudo ./build/dpdkcap -c 0x07 -n 8 -- --portmask 0x1

EAL: Detected 8 lcore(s)
EAL: Probing VFIO support...
PMD: bnxt_rte_pmd_init() called for (null)
EAL: PCI device 0000:01:00.0 on NUMA socket -1
EAL:   probe driver: 8086:10ec rte_ixgbe_pmd
EAL: PCI device 0000:01:00.1 on NUMA socket -1
EAL:   probe driver: 8086:10ec rte_ixgbe_pmd
EAL: PCI device 0000:02:00.0 on NUMA socket -1
EAL:   probe driver: 8086:10ec rte_ixgbe_pmd
EAL: PCI device 0000:02:00.1 on NUMA socket -1
EAL:   probe driver: 8086:10ec rte_ixgbe_pmd
DPDKCAP: Using 1 ports to listen on
DPDKCAP: Using 3 cores out of 3 allocated
EAL: Error - exiting with code: 1
  Cause: Cannot init port 0
DPDKCAP: Core 1 is writing using file template: output_%COREID.pcap.lzo.

Thanks for your help.

**Comment by groud** [comment]
Hi,

As it is indicated by your output, it seems that your error is raised by the EAL part of the software.
Consequently, you might have problem with your DPDK configuration (not with DPDKCap). 

Maybe your interface is not configured to work with the DPDK compatible driver. Have a look to the DPDK documentation for more information.
Try maybe to launch `./dpdk/tools/dpdk_nic_bind.py -s` to check your bindings ?

**Comment by diegodem** [comment]
Yeah, I thought so, but I am able to launch any other DPDK application. 
When I do what you say I get:

# Network devices using DPDK-compatible driver

0000:01:00.1 '82598EB 10-Gigabit AT CX4 Network Connection' drv=uio_pci_generic unused=ixgbe

# Network devices using kernel driver

0000:01:00.0 '82598EB 10-Gigabit AT CX4 Network Connection' if=enp1s0f0 drv=ixgbe unused=uio_pci_generic 
0000:02:00.0 '82598EB 10-Gigabit AT CX4 Network Connection' if=enp2s0f0 drv=ixgbe unused=uio_pci_generic 
0000:02:00.1 '82598EB 10-Gigabit AT CX4 Network Connection' if=enp2s0f1 drv=ixgbe unused=uio_pci_generic 
0000:04:00.0 'NetXtreme BCM5722 Gigabit Ethernet PCI Express' if=eno1 drv=tg3 unused=uio_pci_generic _Active_

# Other network devices

<none>

But I have also tried with igb_uio with the same results.
Thanks

**Comment by groud** [comment]
Oh, I see what happens.
The error is returned by the `port_init` function, an error must occur during the port configuration.
I created a pull request with better logs, can you try to checkout and compile the code, then give me the result of your command ?

**Comment by diegodem** [comment]
This is what I get now:

EAL: Detected 8 lcore(s)
EAL: Probing VFIO support...
PMD: bnxt_rte_pmd_init() called for (null)
EAL: PCI device 0000:01:00.0 on NUMA socket -1
EAL:   probe driver: 8086:10ec rte_ixgbe_pmd
EAL: PCI device 0000:01:00.1 on NUMA socket -1
EAL:   probe driver: 8086:10ec rte_ixgbe_pmd
EAL: PCI device 0000:02:00.0 on NUMA socket -1
EAL:   probe driver: 8086:10ec rte_ixgbe_pmd
EAL: PCI device 0000:02:00.1 on NUMA socket -1
EAL:   probe driver: 8086:10ec rte_ixgbe_pmd
DPDKCAP: Using 1 ports to listen on
DPDKCAP: Using 3 cores out of 8 allocated
DPDKCAP: rte_eth_dev_set_rx_queue_stats_mapping(...) returned with error code -38
EAL: Error - exiting with code: 1
  Cause: Cannot init port 0
DPDKCAP: Core 1 is writing using file template: output_%COREID.pcap.lzo.

Thanks

**Comment by groud** [comment]
I need more information, could you add `--log-level 8` to your EAL arguments ?

**Comment by diegodem** [comment]
The result is just the same :/

**Comment by groud** [comment]
I see. Looking at the DPDK code, it seems that more debug logs can be displayed thanks to a DPDK build option. I think you will have to recompile DPDK with the `RTE_LIBRTE_ETHDEV_DEBUG` option, in the `.config` file.

Let me know if you manage to get better logs. This is the only way I can help you as I cannot reproduce the issue.

PS: I am not sure yet, but if the -38 error code is a system one, it seems to indicate an unimplemented function. See [here](http://www-numi.fnal.gov/offline_software/srt_public_context/WebDocs/Errors/unix_system_errors.html)

**Comment by diegodem** [comment]
I recompiled changing that option but there was no luck... The output is just the same.

**Comment by groud** [comment]
Did you keep the `--log-level 8` option ? I you did not, you have to :)

**Comment by diegodem** [comment]
Yeah, I did... I detail the steps just in case I did something wrong:
-I deleted the directory dpdkcap
-I changed .config and `make`
-I loaded and bind igb_uio
-I cloned dpdkcap again.
-I set the variables and `make`
-`sudo ./build/dpdkcap --log-level 8 -c 0x07 -n 8 -- --portmask 0x1`
-Same output as before

**Comment by diegodem** [comment]
Also I have a twin PC of this (the one meant to generate traffic) but in that one when I try to compile dpdkcap I get:

/home/traffic1/dpdkcap/src/statistics_ncurses.c:4:21: fatal error: ncurses.h: No existe el archivo o el directorio
compilation terminated.

**Comment by groud** [comment]
I have to test if it works, but in any case, for recompiling dpdk:
- Go into the `dpdk` directory
- Run `make config T=x86_64-native-linuxapp-gcc` (or your specific target)
- go into the `x86_64-native-linuxapp-gcc` directory
- modify the `.config` file there
- Go back to the `dpdk` directory
- Run `make`
- Go into `dpdkcap` directory
- Set the variables and make

**Comment by groud** [comment]
And for your other PC problem, you need to install the ncurses library.
If you run ubuntu: `sudo apt-get install libncurses-dev`

**Comment by diegodem** [comment]
Ok, so in the other PC I have the same problem: "Cannot init port 0".

The steps are the same I did, except that I made `make` in the x86_64-native-linuxapp-gcc directory, because if I do `make` in the dpdk directory, it says: No .config in build directory

**Comment by groud** [comment]
Ok, what I would suggest is to add all other debug options for your specific driver (it seems that it is ixgbe)
So in the `.config` file, change all thoses variables to `y`:

```
CONFIG_RTE_LIBRTE_IXGBE_DEBUG_INIT=n
CONFIG_RTE_LIBRTE_IXGBE_DEBUG_RX=n
CONFIG_RTE_LIBRTE_IXGBE_DEBUG_TX=n
CONFIG_RTE_LIBRTE_IXGBE_DEBUG_TX_FREE=n
CONFIG_RTE_LIBRTE_IXGBE_DEBUG_DRIVER=n
```

If it does not display anything else, maybe set to `y` all variable with DEBUG in their names

**Comment by diegodem** [comment]
I set every single DEBUG variable to y, and still nothing :(

**Comment by groud** [comment]
Weird :/
Maybe using `make install` ?

**Comment by diegodem** [comment]
Nothing, just this:
make[2]: No se hace nada para 'pre_install'.
================== Installing /usr/local/
Installation in /usr/local/ complete

**Comment by groud** [comment]
Well ok I think I get it... According to DPDK code it seems that your Ethernet card does not provide the `queue_stats_mapping_set` function. I cannot see where else the error would come from...
Not all apps use this function, but for now DPDKCap needs it. 

I have not the time to clenly modify the code by now, but I think you can comment few lines to make it work: 
In `dpdkcap.c`, comment lines from 184 to 190 (included). (You may try it like that, but I am not sure it will work...)

Else, if it does not work, also comment in `statistics_ncurses.c` lines from 55 to 96 (the for loop)

Note that dpdk wont be able to display ports statistics.

**Comment by diegodem** [comment]
If I comment the lines in dpdkcap.c, when I `make` I get:

 CC src/dpdkcap.o
/home/traffic1/dpdkcap/src/dpdkcap.c: In function ‘port_init’:
/home/traffic1/dpdkcap/src/dpdkcap.c:187:5: warning: multi-line comment [-Wcomment]
     //  RTE_LOG(ERR, DPDKCAP, "rte_eth_dev_set_rx_queue_stats_mapping(...) "\
     ^
/home/traffic1/dpdkcap/src/dpdkcap.c: At top level:
/home/traffic1/dpdkcap/src/dpdkcap.c:194:3: warning: data definition has no type or storage class
   retval = rte_eth_tx_queue_setup(port, 0, TX_RING_SIZE,
   ^
/home/traffic1/dpdkcap/src/dpdkcap.c:194:3: warning: type defaults to ‘int’ in declaration of ‘retval’ [-Wimplicit-int]
/home/traffic1/dpdkcap/src/dpdkcap.c:194:35: error: ‘port’ undeclared here (not in a function)
   retval = rte_eth_tx_queue_setup(port, 0, TX_RING_SIZE,
                                   ^
compilation terminated due to -Wfatal-errors.
/home/traffic1/dpdk-16.07/mk/internal/rte.compile-pre.mk:138: fallo en las instrucciones para el objetivo 'src/dpdkcap.o'
make[1]: *** [src/dpdkcap.o] Error 1
/home/traffic1/dpdk-16.07/mk/rte.extapp.mk:42: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2

**Comment by diegodem** [comment]
Now I get this:

EAL: Detected 8 lcore(s)
EAL: Probing VFIO support...
PMD: bnxt_rte_pmd_init() called for (null)
EAL: PCI device 0000:01:00.0 on NUMA socket -1
EAL:   probe driver: 8086:10ec rte_ixgbe_pmd
EAL: PCI device 0000:01:00.1 on NUMA socket -1
EAL:   probe driver: 8086:10ec rte_ixgbe_pmd
DPDKCAP: Using 1 ports to listen on
DPDKCAP: Using 3 cores out of 8 allocated
DPDKCAP: Port 0 MAC: 00 1b 21 64 51 ee
DPDKCAP: Core 1 is writing using file template: output_%COREID.pcap.lzo.
DPDKCAP: Core 2 is capturing packets for port 0
PMD: ixgbe_dev_rx_queue_start(): Could not enable Rx Queue 0
DPDKCAP: Waiting for all cores to exit

Does this mean that it's working?

**Comment by groud** [comment]
You can try with the `--statistics` option, but it seems that it does work, yes.
Use `ctrl+c` to stop the capture, it should display an exit message and stop.

**Comment by diegodem** [comment]
Ok, thank you. And what's exactly the functionality I've lost?

**Comment by groud** [comment]
Only statical information during the capture. Usually, it should look like that:
![2016-08-26-133655_1278x866_scrot](https://cloud.githubusercontent.com/assets/6093119/18004114/35fd21fc-6b92-11e6-8d07-f81ca5961447.png)
But in your case nothing should be displayed on the right. 

If you do not use the statistics option, nothing changes.

**Comment by diegodem** [comment]
But I actually get this
![stats](https://cloud.githubusercontent.com/assets/20596136/18004327/7b314130-6b93-11e6-9016-382bd2d78145.png)

**Comment by groud** [comment]
So you did not comment the for loop I guess.
Concerning the character problem for the border, I cannot do anything about it. It must come from the terminal emulator or something like that.

**Comment by diegodem** [comment]
I just commented in the dpdkcap.c. I have 100% functionality then?
Don't worry about the characters, it's probably the ssh.

**Comment by groud** [comment]
Well, not really.
As you can see on the right, only the first queue has displayed stats, not the other ones.
I am not sure about what theses stats actually mean then, as you commented the configuration part. Maybe it works, maybe not, I dont know... ^^ So information on the right is not reliable, while everything on the left is.

Anyway that is only for monitoring purpose, it should not affect (at all) the resulting capture.

**Comment by diegodem** [comment]
Ok, thank you for everything.

**Comment by groud** [comment]
You are welcome ! :)

**Comment by aparnasuri** [comment]
Hi,

I see the same error message too. I tried commenting out the code in dpdkcap.c as you had mentioned, but the compilation errors out when I comment the code. This is the error I see :

In function 'port_init':
dpdkcap.c:218:12: error: invalid storage class for function 'port_start'
 static int port_start(uint8_t port) {
            ^
compilation terminated due to -Wfatal-errors.

How do I get this fixed? Or is there any other fix for this issue since the previous post on this thread?

Thanks and Regards,
Aparna

**Comment by groud** [comment]
Hi,
The lines to comment into dpdkcap.c are the following:

```
//Stats bindings
retval = rte_eth_dev_set_rx_queue_stats_mapping (port, q, q);
if (retval < 0) {
  RTE_LOG(ERR, DPDKCAP, "rte_eth_dev_set_rx_queue_stats_mapping(...) "\
      "returned with error code %d\n", retval);
  return retval;
}
```

If you did not changed anything else, it should work without any problem.
