### ISSUE TITLE
Problem with rte_eth_dev_set_rx_queue_stats_mapping

### ISSUE THREAD

**Issue by groud** [dpdkcap/dpdkcap#21]
When a Ethernet device does not handle multiples queues, the `rte_eth_dev_set_rx_queue_stats_mapping` usually does not work.
To make the statistics work, `rte_eth_stats_get` should be used instead.

Maybe it could be interesting to add those stats on the capture side of the statistics, and disable the per queue one if not handled.

**Comment by fastxs** [comment]
DPDKCAP: rte_eth_dev_set_rx_queue_stats_mapping(...) returned with error code -95
DPDKCAP: The queues statistics mapping failed. The displayed queue statistics are thus unreliable.

**Comment by groud** [comment]
Should be fixed by now: if the driver can only handle one queue, the `rte_eth_dev_set_rx_queue_stats_mapping` is not executed.
