### ISSUE TITLE
Mbuf Allocation failures

### ISSUE THREAD

**Issue by qchai** [dpdkcap/dpdkcap#22]
Hi ，
    When I run dpdkcap，it can't capture packages and the result is as follows, I don't know the reason why "Mbuf Allocation failures", do you know what's wrong with it?
Thank you very much. 
![clipboard](https://cloud.githubusercontent.com/assets/20962153/22726980/5b314b68-ee11-11e6-90bc-beb405a34efd.png)

**Comment by groud** [comment]
Hello,
please checkout the last version of the 'develop' branch, there is an option to increase the number of available MBUFs. (the default value is also higher)
This should fix the problem

**Comment by qchai** [comment]
The problem has resolved, Thank you very much.

**Comment by groud** [comment]
You are welcome :)
