### ISSUE TITLE
Cannot create mbuf pool

### ISSUE THREAD

**Issue by qchai** [dpdkcap/dpdkcap#24]
Hi, 
    I have used dpdkcap-develop to capture packages, and it works OK, but now it can't work, and the error is as below:
[root@localhost dpdkcap-develop]# ./build/dpdkcap -c 0xf -n 2 -- -p 0x1 --statistics
EAL: Detected 4 lcore(s)
EAL: Probing VFIO support...
EAL: PCI device 0000:03:00.0 on NUMA socket -1
EAL:   probe driver: 15ad:7b0 net_vmxnet3
EAL: PCI device 0000:0b:00.0 on NUMA socket -1
EAL:   probe driver: 15ad:7b0 net_vmxnet3
DPDKCAP: Using 1 ports to listen on
DPDKCAP: Using 3 cores out of 4 allocated
EAL: Error - exiting with code: 1
  Cause: Cannot create mbuf pool

I just add memory of my virtual machine , I don't know whether  it cause the error, do you have any idea?
Thank you very much.

**Comment by groud** [comment]
Hi,
You can use the `-m` option to reduce the number of memory buffers (mbufs).
Choose something like 4095 (a power of 2 minus one), the nit might work.

I will add that to the README file.

**Comment by qchai** [comment]
Well, It works OK.
I just curious why sometimes it work well with -m 65535 or even bigger, but sometimes must reduce the number of -m, whether it is related with the port traffic of the real network, or  it associated to memory usage?
Thank you very much.

**Comment by groud** [comment]
This value mainly depends on how much memory you give to dpdkcap (the number of hugepages and their size). I would say that the more hugepages you have, the better it is, but it should not go over your hugepages limitations. Usually, the number of mbufs only impact your ability to handle short traffic peaks.

I am not sure about that, but I believe there is a minimum value for the number of mbufs. Too low values could cause mbufs allocations failures, especially if you use a large amount of RX descriptors.

**Comment by qchai** [comment]
Thank you very much for your help :)
