### ISSUE TITLE
Build failure as method is deprecated

### ISSUE THREAD

**Issue by PhilipDeegan** [dpdkcap/dpdkcap#26]
Error

```
pdkcap/src/dpdkcap.c:416:3: error: ‘rte_set_log_type’ is deprecated
```

[link](http://dpdk.org/browse/dpdk/tree/lib/librte_eal/common/include/rte_log.h#n169)

This is with the current dpdk master

**Comment by Woutifier** [comment]
Hi Dekken,

Thank you for your issue report. We will look into it. We probably will want to mention in the README.md that we test against the current stable DPDK release.

http://dpdk.org/browse/dpdk/commit/lib/librte_eal/common/include/rte_log.h?id=4f0981e6ec6c6ae99c9866c4e19f7a496ac95076.
```
Deprecate the following functions:
- rte_set_log_level(), replaced by rte_log_set_global_level()
- rte_get_log_level(), replaced by rte_log_get_global_level()
- rte_set_log_type(), replaced by rte_log_set_level()
- rte_get_log_type(), replaced by rte_log_get_level()

The new functions provide a better control of the per-type log level,
and have a better name prefix (rte_log_).
```
@groud It would probably be worthwhile to set up the CI to test against the dpdk master as well?

**Comment by groud** [comment]
@Woutifier yes, that would be a good idea. I see multiple think to do:
- Choose the version of DPDK with which we start to "maintain" the project.
- Set a version check into the code (using [the version api](http://dpdk.org/doc/api/rte__version_8h.html)).
- Set tests in the CI for each of these "major" version.
- Add the supported versions in the README.md file

Unfortunatly, it seems that DPDK does not use the concept on "major release". Instead the version number uses a "year.month.minor" format. I guess year.month corresponds to API changes ?

**Comment by PhilipDeegan** [comment]
Hi @Woutifier , yes I downloaded the latest [major](http://dpdk.org/download) (17.02) version and that works just fine
