### ISSUE TITLE
Question - Splitting capture files based on IP/ports

### ISSUE THREAD

**Issue by PhilipDeegan** [dpdkcap/dpdkcap#27]
Hi there,

I'm having trouble getting DPDK working in any capacity (I suspect it's a hugetlb problem)

But I'm trying to verify if this tool is even sufficient for my needs, one being that I can split the capture (pcap?) into different files or even directories to allow for parrallel playback/processing.

Thanks

**Comment by groud** [comment]
Well, here are a few tips regarding performances:
- limit the number of capture cores to 1 per port with `-c 1` as option
- Use as many writing core as possible.
- Read the DPDK manual for more information on core assignment => disable hyperthreading and choose cores on the same socket.

In any case DPDKcap allready process the traffic using multiple cores (it uses the DPDK dedicated API)
 
You will allways have one file for each writting core, but there is for the moment no option to split the capture according to IP/ports. You will have to do that by post-processing the capture files.
I know how we could implement it, but this would require a lot of time, which I don't have for now :/

**Comment by xaki23** [comment]
i am not sure what the original goal here was.

if just for convenience:
splitting into different files/dirs based on ip/port works with the BPF filtering now: https://github.com/dpdkcap/dpdkcap/issues/17

if for performance/balancing:
use more writer cores. (and filtering either in writer threads or from disk postprocessing)
some pre-splitting could also be used on the capture cores by using the right RSS flags, but that depends _very_ much on usecase and hardware.

lacking specifics of the question, this issue can probably be closed for now.
