### ISSUE TITLE
error in compiling dpdk 17.05

### ISSUE THREAD

**Issue by fastxs** [dpdkcap/dpdkcap#28]
Try dpdk 17.05:
# make
  CC src/dpdkcap.o
/home/gc/dpdkcap/src/dpdkcap.c: In function ‘main’:
/home/gc/dpdkcap/src/dpdkcap.c:416:3: warning: ‘rte_set_log_type’ is deprecated (declared at /usr/local/share/dpdk/x86_64-native-linuxapp-gcc/include/rte_log.h:169) [-Wdeprecated-declarations]
   rte_set_log_type(RTE_LOGTYPE_DPDKCAP, 1);
   ^
/home/gc/dpdkcap/src/dpdkcap.c:417:3: warning: ‘rte_set_log_level’ is deprecated (declared at /usr/local/share/dpdk/x86_64-native-linuxapp-gcc/include/rte_log.h:144) [-Wdeprecated-declarations]
   rte_set_log_level(RTE_LOG_DEBUG);
   ^
  CC src/core_write.o
/home/gc/dpdkcap/src/core_write.c: In function ‘write_core’:
/home/gc/dpdkcap/src/core_write.c:231:9: error: too few arguments to function ‘rte_ring_dequeue_bulk’
         DPDKCAP_WRITE_BURST_SIZE);
         ^
compilation terminated due to -Wfatal-errors.
make[1]: *** [src/core_write.o] Error 1
make: *** [all] Error 2

17.05 apparently added another argument

**Comment by groud** [comment]
Should be fixed in the develop branch. If you've got the time to check if it works well, feel free to do so. :)

**Comment by fastxs** [comment]
yes build success but when you run, got coredump. will dig more

**Comment by groud** [comment]
Closing, as this is now a segfault issue.
