### ISSUE TITLE
Packets received but none written

### ISSUE THREAD

**Issue by aleczadikian** [dpdkcap/dpdkcap#29]
I'm running a test application and capturing packets with the "-S" option enabled. The stats say "RX successful packets: 227" and "RX successful bytes: 13.30 KB", but the per core writing stats say 0 bytes written. And the output file is empty except for the header. What could be causing this to happen?

This was printed before, if it's relevant:
```
DPDKCAP: rte_eth_dev_set_rx_queue_stats_mapping(...): Function not implemented
DPDKCAP: The queues statistics mapping failed. The displayed queue statistics are thus unreliable.
```

DPDK version: dpdk-stable-16.07.1
RTE_target: x86_64-native-linuxapp-gcc
Started with ./build/dpdkcap -c 0x0000f0000 --socket-mem 128,4096 -w 0000:83:00.0 -w 0000:83:00.1 -- --no-compression -S -G 10

**Comment by groud** [comment]
Hum, did you close dpdkcap before checking the file ?
The file writing works by batches, the remaining content is usually flushed when you close dpdkcap.

**Comment by aleczadikian** [comment]
Yes, I also closed it then checked the file to see that it was empty. But dpdkcap's stats were showing 0 packets written, and it looks like that's counting as it's writing regardless of what is flushed to disk. 

Anyway, I came back to report that I've found it doesn't happen if I start dpdkcap _after_ my other test program has already started sending packets (rather than starting it before and leaving it running throughout). I see the rx stats are taken using a different DPDK function call from what is used to collect packets and update the write stats. Perhaps there are too many moving parts here to assess the problem, and it might be specific to my setup.

Also, here's a snippet of a bad output:

```┌─Global stats─────────────────────────────────────────────┐┌─Capture stats────────────────────────────────────────────┐
│Writing logs to stderr                                    ││    Packets/s: 0                                          │
│Entries free on ring: 8191                                ││                                                          │
│                                                          ││PORT 1:                                                   │
│                                                          ││  RX Successful bytes: 21.27 KB (avg: 183 bytes/pkt)      │
│                                                          ││  RX Successful packets: 119                              │
│                                                          ││  RX Unsuccessful packets: 0                              │
│                                                          ││  RX Missed packets: 244                                  │
│                                                          ││  MBUF Allocation failures: 0                             │
└──────────────────────────────────────────────────────────┘│  Per queue:                                              │
┌─Write stats──────────────────────────────────────────────┐│  - Queue  0 handled by core 15:                          │
│Instant compressed/uncompressed size ratio: 1 / 0.00      ││           HW:       RX: 0  RX-Error: 0                   │
│                                                          ││         Ring: Enqueued: 0  Missed: 0                     │
│  Per core stats:                                         ││    Packets/s: 0                                          │
│Writing core 13: output_13.pcap (0.00 B)                  ││                                                          │
│                                                          ││                                                          │
DPDKCAP: Waiting for all cores to exit─────────────────────┘└──────────────────────────────────────────────────────────┘```

**Comment by xaki23** [comment]
Closing this since there have not been updates to this issue in a long time and it is about really old versions of DPDK / dpdkcap. 

undecided about this one, because the symptom is something i re-introduced when adding tasks.
currently tasks being removed/dropped does not have a full/proper cleanup code path, so the last/current file of a task that is being dropped will a) leak the FD and all buffers and b) never be fully flushed.
this should be resolved by refactoring the writer code.
