### ISSUE TITLE
Compatible with vmxnet3?

### ISSUE THREAD

**Issue by huanweisu** [dpdkcap/dpdkcap#30]
Hi, I follow the instruction to install DPDK(17.05) and dpdkcap(develop branch), could not start dpdkcap normally, after I turn on the DEBUG on $RTE_TARGET/.config and --log-level 8, hear is the error message.
I saw the Device activation: UNSUCCESSFUL so I am wondering does it work on vmxnet3(ESXi 5.5)? thanks.
#sudo build/dpdkcap -c 0x07 -n 2 --log-level 8
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 1 on socket 0
EAL: Detected lcore 2 as core 0 on socket 0
EAL: Detected lcore 3 as core 1 on socket 0
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 4 lcore(s)
Skipping unuse nic message
EAL: PCI device 0000:03:00.0 on NUMA socket -1
EAL:   probe driver: 15ad:7b0 net_vmxnet3
EAL:   PCI memory mapped at 0x7f729d600000
EAL:   PCI memory mapped at 0x7f729d601000
EAL:   PCI memory mapped at 0x7f729d602000
PMD: eth_vmxnet3_dev_init():  >>
PMD: eth_vmxnet3_dev_init(): Hardware version : 1
PMD: eth_vmxnet3_dev_init(): Using device version 1

PMD: eth_vmxnet3_dev_init(): UPT hardware version : 1
PMD: eth_vmxnet3_dev_init(): MAC Address : 00:0c:29:15:d8:1c
DPDKCAP: Using 1 ports to listen on
DPDKCAP: Using 3 cores out of 3 allocated
PMD: vmxnet3_dev_configure():  >>
PMD: vmxnet3_dev_rx_queue_setup():  >>
DPDKCAP: rte_eth_dev_set_rx_queue_stats_mapping(...): Operation not supported
DPDKCAP: The queues statistics mapping failed. The displayed queue statistics are thus unreliable.
DPDKCAP: Port 0: MAC=00:0c:29:15:d8:1c, RXdesc/queue=512
DPDKCAP: Core 2 is capturing packets for port 0
PMD: vmxnet3_recv_pkts(): Rx queue is stopped.
PMD: vmxnet3_recv_pkts(): Rx queue is stopped.
PMD: vmxnet3_recv_pkts(): Rx queue is stopped.
PMD: vmxnet3_recv_pkts(): Rx queue is stopped.
PMD: vmxnet3_recv_pkts(): Rx queue is stopped.
PMD: vmxnet3_recv_pkts(): Rx queue is stopped.
PMD: vmxnet3_recv_pkts(): Rx queue is stopped.
PMD: vmxnet3_recv_pkts(): Rx queue is stopped.
PMD: vmxnet3_recv_pkts(): Rx queue is stopped.
PMD: vmxnet3_recv_pkts(): Rx queue is stopped.
PMD: vmxnet3_recv_pkts(): Rx queue is stopped.
PMD: vmxnet3_recv_pkts(): Rx queue is stopped.
PMD: vmxnet3_recv_pkts(): Rx queue is stopped.
PMD: vmxnet3_dev_start():  >>
PMD: vmxnet3_recv_pkts(): Rx queue is stopped.
PMD: vmxnet3_recv_pkts(): Rx queue is stopped.
PMD: vmxnet3_recv_pkts(): Rx queue is stopped.
PMD: vmxnet3_recv_pkts(): Rx queue is stopped.
PMD: vmxnet3_recv_pkts(): Rx queue is stopped.
PMD: vmxnet3_recv_pkts(): Rx queue is stopped.
PMD: vmxnet3_recv_pkts(): Rx queue is stopped.
PMD: vmxnet3_recv_pkts(): Rx queue is stopped.
PMD: vmxnet3_recv_pkts(): Rx queue is stopped.
PMD: vmxnet3_write_mac(): Writing MAC Address : 00:0c:29:15:d8:1c
PMD: vmxnet3_dev_start(): Device activation: UNSUCCESSFUL
EAL: Error - exiting with code: 1
  Cause: Cannot start port 0

**Comment by groud** [comment]
No idea what is happening, but may be linked to #31

**Comment by xaki23** [comment]
Closing this since there have not been updates to this issue in a long time and it is about really old versions of DPDK / dpdkcap.
