### ISSUE TITLE
Segmentation fault when starting dpdkcap on 17.05

### ISSUE THREAD

**Issue by bkuhre** [dpdkcap/dpdkcap#31]
When I start dpdkcap in 17.05 it makes a segmentation fault.

# ./build/app/dpdkcap  -c 0x7
EAL: Detected 32 lcore(s)
EAL: Probing VFIO support...
EAL: PCI device 0000:09:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1533 net_e1000_igb
EAL: PCI device 0000:0a:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1533 net_e1000_igb
DPDKCAP: Using 1 ports to listen on
DPDKCAP: Using 3 cores out of 3 allocated
DPDKCAP: rte_eth_dev_set_rx_queue_stats_mapping(...): Operation not supported
DPDKCAP: The queues statistics mapping failed. The displayed queue statistics are thus unreliable.
DPDKCAP: Port 0: MAC=0c:c4:7a:db:86:e8, RXdesc/queue=512
DPDKCAP: Core 2 is capturing packets for port 0
DPDKCAP: Core 1 is writing using file template: output_%COREID.pcap.lzo.
Segmentation fault

It seems to be an error in 17.05 as the it works fine with 17.02. 

Am I doing something wrong?

**Comment by groud** [comment]
Related to #28.
I however don't have the time to work on that, a PR would be welcome.

**Comment by TCZWJ** [comment]
The interface rte_ring_dequeue_bulk of 17.02 and 17.05 has changed. Moreover,the "dequeued[i]" in the code of src/core_write.c is probably NULL ptr.

**Comment by xaki23** [comment]
Closing this since there have not been updates to this issue in a long time and it is about really old versions of DPDK / dpdkcap.
