### ISSUE TITLE
error: too few arguments to function ‘rte_ring_dequeue_bulk

### ISSUE THREAD

**Issue by qwe131829** [dpdkcap/dpdkcap#34]
I met this error when I was compiling. I think there are fewer parameters in the function, but the source code is not less.I'm still looking for the wrong reason. if the original author find this issue ,please tell me .

**Comment by 8-5-0** [comment]
If you build from git, don't use "master" branch, it doesn't work. Use develop branch instead.

**Comment by xaki23** [comment]
Closing this since there have not been updates to this issue in a long time and it is about really old versions of DPDK / dpdkcap.
