### ISSUE TITLE
Error: No port available.

### ISSUE THREAD

**Issue by maialenzab** [dpdkcap/dpdkcap#35]
Hi, I'm trying to run dpdkcap but when I execute this command 

`sudo ./build/dpdkcap -c 0x0f -n 2 -- -c 1 -w 2` I get the following error: 
```           
EAL: Detected 4 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: Error - exiting with code: 1
  Cause: Error: No port available.
```
Any ideas?
DPDK Version - 17.02.1

### Network devices using DPDK-compatible driver
============================================
0000:01:00.0 'I210 Gigabit Network Connection' drv=igb_uio unused=igb

### Network devices using kernel driver
===================================
0000:02:00.0 'I210 Gigabit Network Connection' if=enp2s0 drv=igb unused=igb_uio *Active*
0000:03:00.0 'I210 Gigabit Network Connection' if=enp3s0 drv=igb unused=igb_uio 
0000:04:00.0 'QCA986x/988x 802.11ac Wireless Network Adapter' if=wlp4s0 drv=ath10k_pci unused=igb_uio

**Comment by xaki23** [comment]
Closing this since there have not been updates to this issue in a long time and it is about really old versions of DPDK / dpdkcap.
