### ISSUE TITLE
Segmentation fault on rte_eth_dev_start function of 18.11

### ISSUE THREAD

**Issue by JotusKuo** [dpdkcap/dpdkcap#36]
I got a segmentation fault based on DPDK18.11 using develop branch. And I found dpdkcap crashed on rte_eth_dev_start function in main by my preliminary debugging by adding RTE_LOG at line 597 and 601. 
The steps are as following,
1. cd /path/of/dpdk-18.11
2. export RTE_SDK and RTE_TARGET
3. ./usertools/dpdk-setup.sh
4. choose [15] x86_64-native-linuxapp-gcc, [18] Insert IGB UIO module, [21] Setup hugepage mappings for non-NUMA systems setting 2048, and [24] Bind Ethernet/Crypto device to IGB UIO module setting 0000:82:00.0, [35]
5. cd /path/to/dpdkcap
6. make getting 4 warning about ‘rte_eth_dev_count’ is deprecated
7. sudo -E ./build/dpdkcap -c 0xff00 -n 4

**EAL: Detected 32 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:05:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1533 net_e1000_igb
EAL: PCI device 0000:06:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1533 net_e1000_igb
EAL: PCI device 0000:82:00.0 on NUMA socket 1
EAL:   probe driver: 8086:10fb net_ixgbe
DPDKCAP: Using 1 ports to listen on
DPDKCAP: Using 3 cores out of 8 allocated
DPDKCAP: Port 0: MAC=00:1b:21:7e:4d:06, RXdesc/queue=512
DPDKCAP: Core 9 is writing using file template: output_%COREID.pcap.lzo.
DPDKCAP: Line 597 Warning: portId 0, for debug 6666666666666666666666666666666.
Segmentation fault**

Any suggestion?

**Comment by xaki23** [comment]
Closing this since there have not been updates to this issue in a long time and it is about really old versions of DPDK / dpdkcap.
