### ISSUE TITLE
EAL Initializing port 0 

### ISSUE THREAD

**Issue by lizihan8** [dpdkcap/dpdkcap#39]
Initializing port 0... EAL: Error - exiting with code: 1
Cause: rte_eth_tx_queue_setup:err=-22, port=0, queueid: 0

**Comment by TCZWJ** [comment]
which is the version of DPDK、OS？

**Comment by vipinpv85** [comment]
If DPDK is built with shared libraries, one has to pass `-d [nic driver pmd shared library]` to instantiate the same.  You can get more information by using `--log-level=pmd,8` too

**Comment by xaki23** [comment]
Closing this since there have not been updates to this issue in a long time and it is about really old versions of DPDK / dpdkcap.
