### ISSUE TITLE
Do not exit if not stats are available (rte_eth_dev_set_rx_queue_stats_mapping returns -95)

### ISSUE THREAD

**Issue by groud** [dpdkcap/dpdkcap#4]
The problem occured with #2.
If the stats queue mapping cannot be configured, the app should display a warning, but operate anyway.

**Comment by groud** [comment]
Fixed

**Comment by qchai** [comment]
Hi，
   when I try to capture packets , I see the problem as follows:
 ./build/dpdkcap -c 0xf -n 2 -- -p 0x1
EAL: Detected 4 lcore(s)
EAL: Probing VFIO support...
PMD: bnxt_rte_pmd_init() called for (null)
EAL: PCI device 0000:02:03.0 on NUMA socket -1
EAL:   probe driver: 8086:100f rte_em_pmd
EAL: PCI device 0000:02:04.0 on NUMA socket -1
EAL:   probe driver: 8086:100f rte_em_pmd
EAL: PCI device 0000:03:00.0 on NUMA socket -1
EAL:   probe driver: 15ad:7b0 rte_vmxnet3_pmd
DPDKCAP: Using 1 ports to listen on
DPDKCAP: Using 3 cores out of 4 allocated
DPDKCAP: rte_eth_dev_set_rx_queue_stats_mapping(...) returned with error code -95
DPDKCAP: The queues statistics mapping failed. The displayed queue statistics are thus unreliable.
DPDKCAP: Port 0 MAC: 00 0c 29 de dc 2b
DPDKCAP: Core 1 is writing using file template: output_%COREID.pcap.lzo.
DPDKCAP: Core 2 is capturing packets for port 0
PMD: em_alloc_rx_queue_mbufs(): RX mbuf alloc failed queue_id=0
PMD: eth_em_start(): Unable to initialize RX hardware
EAL: Error - exiting with code: 1
  Cause: Cannot start port 0

   Can you help me to see what's wrong?
   Thank you very much.

**Comment by groud** [comment]
This is a problem due to the last version and will be fixed soon (I am waiting for an answer on DPDK's users mail list)
You can checkout the b34a59e67779662a6db425327b49cf0e1daf6186 commit, this is the last commit before the problematic one.

**Comment by groud** [comment]
It might be fixed by now on the last commit of the develop branch.
