### ISSUE TITLE
Core dump

### ISSUE THREAD

**Issue by yangye-huaizhou** [dpdkcap/dpdkcap#40]
The output is as follow:

DPDKCAP: Using 1 ports to listen on
DPDKCAP: Using 3 cores out of 3 allocated
DPDKCAP: Port 0: MAC=e8:61:1f:16:cc:5d, RXdesc/queue=512
DPDKCAP: Core 2 is capturing packets for port 0
DPDKCAP: Core 1 is writing using file template: output_%COREID.pcap.
Segmentation fault (core dumped)

**Comment by yangye-huaizhou** [comment]
I found the problem.
In core_write.c

311 #if RTE_VERSION >= RTE_VERSION_NUM(17,5,0,16)
312     to_write = rte_ring_dequeue_bulk(config->ring, (void*) dequeued,
313         DPDKCAP_WRITE_BURST_SIZE, NULL);
314 #else
315     to_write = rte_ring_dequeue_bulk(config->ring, (void*) dequeued,
316         DPDKCAP_WRITE_BURST_SIZE);
317 #endif
318     if (likely(to_write==0)) {
319       to_write = DPDKCAP_WRITE_BURST_SIZE;
320     } else {
321 #if RTE_VERSION >= RTE_VERSION_NUM(17,5,0,16)
322       to_write = rte_ring_dequeue_burst(config->ring, (void*)dequeued,
323           DPDKCAP_WRITE_BURST_SIZE, NULL);
324 #else
325       to_write = rte_ring_dequeue_burst(config->ring, (void*)dequeued,
326           DPDKCAP_WRITE_BURST_SIZE);
327 #endif
328     }

it's a logical error. Modify the line 318 to "if (likely(to_write!=0))". That works for me.

**Comment by groud** [comment]
Could you make a PR ?

**Comment by yangye-huaizhou** [comment]
I have sent the PR.
And I found another problem.
when the traffic gets very large( more than 3Gbps ), the cores exit.
CMD shows:

DPDKCAP: Using 1 ports to listen on
DPDKCAP: Using 3 cores out of 3 allocated
DPDKCAP: Port 0: MAC=e8:61:1f:16:cc:5d, RXdesc/queue=512
DPDKCAP: Core 2 is capturing packets for port 0
DPDKCAP: Core 1 is writing using file template: output_%COREID.pcap.
DPDKCAP: Waiting for all cores to exit
DPDKCAP: Could not write into file: 0 (Success)
DPDKCAP: Closed writing core 1
DPDKCAP: Core 1 did not stop correctly.
^CDPDKCAP: Caught signal Interrupt on core 0 (MASTER CORE)
DPDKCAP: Closed capture core 2 (port 0)

**Comment by yangye-huaizhou** [comment]
Some mbufs' datalen are 0, I have never seen this in DPDK programs.
Looks like a synchronization problem between write core and capture core.

**Comment by tengliu0929** [comment]
I also got a coredump when call  rte_ring_dequeue_bulk, the return value is 256, and the pointer dequeued is NULL, I don't konw where the the problem. Besides, I deploy a centos 7 server in vmvare virtual machine and two all nic is virtual, I don't konw if this is the reason for coredump.  And what I want to know is the version of dpdk. I use dpdk 18.11 and I found some functions have beed deprecated, so I rewrite some area.

**Comment by yangye-huaizhou** [comment]
Yes!
You are right. Some APIs are changed in the later version of DPDK and now I have fixed the problem in my fork's.

**Comment by tengliu0929** [comment]
Could this program run in a virtual machine?  And  how to confiure the virtual nic and cpu, I have no idea about how to configure, any advices could you give me ? Thanks.

**Comment by yangye-huaizhou** [comment]
My answer is yes.
But if you want to run DPDK program in VMware, you may meet one problem about the emulated e1000 virtual NIC. 
I remember you can modify a configure file to use the DPDK program.
My suggestion is you can first allocate one e1000 NIC and at least 2 cores for the VM.
Then compile the DPDK, insmod module, bind the NIC driver and run l2fwd program.
If you want to know more about the DPDK configuration, you can read my blog:
https://ictyangye.github.io/dpdk/2017/05/10/DPDK-installer.html
and
https://ictyangye.github.io/dpdk/2017/09/22/DPDK-l2fwd.html
This program is very similar to l2fwd.
If you still have any questions, welcome
