### ISSUE TITLE
Unable to compile via make: ETHER_MAX_LEN

### ISSUE THREAD

**Issue by sameerkhanna786** [dpdkcap/dpdkcap#43]
error: ‘ETHER_MAX_LEN’ undeclared here (not in a function); did you mean ‘RTE_ETHER_MAX_LEN’

How do I fix this?
Using 18.11.5-0ubuntu0.19.04.1
And target as x86_64-native-linux-gcc

**Comment by lvpenglive** [comment]
I had the same problem

**Comment by lvpenglive** [comment]
> 错误：此处未声明“ ETHER_MAX_LEN”（不在函数中）；你是说'RTE_ETHER_MAX_LEN'
> 
> 我该如何解决？
> 使用18.11.5-0ubuntu0.19.04.1 
> 并将目标作为x86_64-native-linux-gcc

use dpdk 18.11

**Comment by xaki23** [comment]
Closing this since there have not been updates to this issue in a long time and it is about really old versions of DPDK / dpdkcap.
(i am pretty sure this particular issue is fixed currently)
