### ISSUE TITLE
MTU can be modified？

### ISSUE THREAD

**Issue by lvpenglive** [dpdkcap/dpdkcap#46]
Can I modify the default mtu1500 to 9612？

**Comment by lvpenglive** [comment]
I have a problem. When I grab packets, data longer than 1518 will be discarded, because the default MTU of dpdk is 1500. Is there any way to modify it? I'm a java developer, I don't know much about C

**Comment by lvpenglive** [comment]
Thank you

resolved

**Comment by lvpenglive** [comment]
Thank you

Already

Solve

**Comment by xaki23** [comment]
Closing this since there have not been updates to this issue in a long time and it is about really old versions of DPDK / dpdkcap. 

i have not run into any problems with MRU size yet, but that may depend on the hardware used?
i am curious what your solution was.
