### ISSUE TITLE
How to multi port Pcap capture?

### ISSUE THREAD

**Issue by git-hub-p** [dpdkcap/dpdkcap#48]
I can 0x01 port Pcap Capture, but can't 0x02 pcap capture.

how to 0x01, 0x02, 0x0... port pcap capture?

 commad is 
./dpdkcap --proc-type=primary -m 4095 -c 0xf -n 1 -- -p 0x1 -o $output_path/test --no-compression
==> Capture Start OK,
DPDKCAP: Port 0: MAC:xx:xx:xx:xx:xx:xx, Rxdsc/queue=512
DPDKCAP: Core 2 is capturing packet for port 0
DPDKCAP: Waiting for all cores to exit

./dpdkcap --proc-type=secondary -m 4095 -c 0xf -n 1 -- -p 0x2 -o $output_path/test2 --no-ompression
==>ERROR:
EAL: Error - exiting with code: 1
  Cause: Cannot create mbuf pool

cat /etc/meminfo | grep Huge
AnonHugePages: 29001728 KB
HugePages_Total: 8196
HugePages_Free: 6147
HugePages_Rsvd: 0
HugePages_Surp: 0
Hugepagesize: 2048 KB

how to multi port capture?
dpdk-pdump
use command: ./dpdk-pdump -l 3,4,5 -- --multi --pdump 'port=0,queue=*,rx-dev=/tmp/rx-1.pcap' --pdump 'port=1,queue=*,rx-dev=/tmp/rx-2.pcap'

I wan file split to time and File Size...

help

**Comment by vipinpv85** [comment]
For DPDKPDUMP utility I do not think there is option for splitting file based on time or size. Please check [dpdk pdump documentation](https://doc.dpdk.org/guides/tools/pdump.html)

**Comment by git-hub-p** [comment]
For dpdkcap Is multi port packet capture AND splitting file Possible?

If so, what is the command?

**Comment by vipinpv85** [comment]
> For dpdkcap Is multi port packet capture AND splitting file Possible?
> 
> If so, what is the command?

I have already answered above there is no option for splitting file.

**Comment by git-hub-p** [comment]
Sorry, I got it..

AND multi port capture is Possible?
I can only capture one port.. 
Please answer by looking at the above error..


interface: 4port Intel Ethernet Controller X710 10GBe (i40e)
OS: Centos 7
dpdk: dpdk-stable 19.11.6

**Comment by vipinpv85** [comment]
DPDK Pdump had been enhanced to capture on multiple ports with multiple threads from `19.11`. From official documentation 

```doc
The --multi command line option is optional argument. If passed, capture will be running on unique cores for all --pdump options. If ignored, capture will be running on single core for all --pdump options.
```

Since you have 4 ports, you should least have 4 lcores for using `multi`. Edit your cmdline argument from `-l 3,4,5` to `-l 3-7`.

**Comment by git-hub-p** [comment]
Thankyou. !

Do you have the same cmdline in dpdkcap same cmline argument?
"--muliti" dpdkcap command not found.

**Comment by vipinpv85** [comment]
> Thankyou. !
> 
> dpdkcap same cmline argument?
> "--muliti" dpdkcap command not found.

what is your DPDK version?

**Comment by git-hub-p** [comment]
> > Thankyou. !
> > dpdkcap same cmline argument?
> > "--muliti" dpdkcap command not found.
> 
> what is your DPDK version?

dpdk version is dpdk-stable 19.11.6
I wan file split And save rotate time by minutes.
file format: rx-%H%M_%S.pcap.

but, dpdk-pdump does not have options.
so, I found source to split file by packet count in dpdkcap.
and..
dpdkcap does not have multi port capture options..

I cant programing c, c++.

**Comment by vipinpv85** [comment]
> dk version is dpdk-stable 19.11.6

I am confused, in your earlier reply you state `option --multi is not there`, but now you are saying `file split and rotate based on minutes does not have options`.

I have answered all your questions, and clearly what is supported and not supported. I am done, there is nothing more I have to share.

**Comment by git-hub-p** [comment]
Thank for you.
my question is dpdkcap lib how to multi port capture.
Sorry for confusing the question.
I will read documentation.

**Comment by vipinpv85** [comment]
> Thank for you.
> my question is dpdkcap lib how to multi port capture.
> Sorry for confusing the question.
> I will read documentation.

For the question of `dpdkcap multi thread and multiport capture` you will have to get in touch with author of DPDKCAP. DPDK-PDUMP is not DPDKCAP

**Comment by xaki23** [comment]
Closing this since there have not been updates to this issue in a long time and it is about really old versions of DPDK / dpdkcap. 

it also seems to be _mostly_ about some tool that is not dpdkcap?!
