### ISSUE TITLE
RX packet missed

### ISSUE THREAD

**Issue by tonejk1** [dpdkcap/dpdkcap#52]
Hello,

I am having missed packets when I am capturing a flow of packets (1GB/s with 1024 byte each packet). I am using Ubuntu 18.04 and DPDK 16.11. 

The PC is writing on a hard disk that has a writing  speed of 90 Mb/s . The hugepages used are 4GB with 2MB of size. The  RX file descriptors are modified to 4096 (maximum value). The Mbuf is used by its default value.

What should I do in order not to have have missed packets?

Thank you

**Comment by xaki23** [comment]
are they actualy reported as "missed"? or "no mbuf"?

note 90MB/s disk will be borderline for 1Gbit/s traffic. are you writing compressed or uncompressed?
have you tried cranking up mbufs a lot? (that would allow more buffering between capture and disk)

**Comment by tonejk1** [comment]
It is writing RX missed. Well I changed the ethernet card from a PCI-X to a PCIe one and it is working now. I don't know why

**Comment by xaki23** [comment]
closing this for now since it seems to be resolved by changing out a problematic NIC for a less problematic one.
