### ISSUE TITLE
Filter vlan packet failed

### ISSUE THREAD

**Issue by Refraction0602** [dpdkcap/dpdkcap#55]
Hello,
I have set a bpf task like "tcp", then run the dpdkcap, but after the packet replay, I only got tcp packet without vlan.
Are there any options for vlan compatibility? 
or i have to add RTE_ETH_RX_OFFLOAD_VLAN_STRIP and RTE_ETH_RX_OFFLOAD_QINQ_STRIP to remove vlan?

Thanks.

**Comment by xaki23** [comment]
not sure i fully understand the problem.
you have a filter like "tcp" and want it to match both untagged and vlan tagged packets?
try "tcp or ( vlan and tcp )".
this is generic pcap/bpf matching though, not dpdkcap specific.

**Comment by Refraction0602** [comment]
> not sure i fully understand the problem. you have a filter like "tcp" and want it to match both untagged and vlan tagged packets? try "tcp or ( vlan and tcp )". this is generic pcap/bpf matching though, not dpdkcap specific.

Yes, you got it right.
I have three tcp packets and one of them has a vlan tag.  I can only get two packets without vlan tag if i set the bpf "tcp".
But when I use tcpdump, like "tcpdump -i enp4s0f1 tcp", it's ok to capture all three packets.
So what's the difference between them?

**Comment by xaki23** [comment]
i am not sure why your tcpdump would behave like that.
it very much doesnt do that here:
```
# tcpdump -n -n -r ring-2023-11-16-15-59-c02.pcap "vlan and tcp" | wc -l
reading from file ring-2023-11-16-15-59-c02.pcap, link-type EN10MB (Ethernet)
572285
# tcpdump -n -n -r ring-2023-11-16-15-59-c02.pcap "tcp" | wc -l
reading from file ring-2023-11-16-15-59-c02.pcap, link-type EN10MB (Ethernet)
0
```
(this file contains mainly vlan-tagged traffic, so this is the expected result)

**Comment by Refraction0602** [comment]
If I use the "-r" parameter, the result is the same. 
The difference is that the traffic in the previous result came from the interface (via tcpreplay), and maybe the kernel did some special work to handle the vlan.
So I think this issue has nothing to do with dpdkcap.
Thank you very much. @xaki23

**Comment by xaki23** [comment]
oh, yes, good point about the "file vs interface" difference.
in dpdkcap the bpf matching is done purely in software, on the writer threads/cores. 
this way you can have multiple filters applied to each packet, and for example write all tcp to one file, all udp to another, and all vlan tagged to a third.
and even though that means you have to apply multiple bpf "programs" to each packet, it isnt too bad thanks to CPU caching. 

i am closing this issue for now. if you have more questions, just reopen it or file a new one.
