### ISSUE TITLE
ncurses.h: No such file or directory

### ISSUE THREAD

**Issue by aghasi** [dpdkcap/dpdkcap#7]
When i run "make" command in Ubuntu 16.04 following error appears:
root@ubuntu:~/dpdkcap# make
  CC src/dpdkcap.o
  CC src/core_write.o
  CC src/core_capture.o
  CC src/statistics_ncurses.o
/home/sub/dpdkcap/src/statistics_ncurses.c:4:21: fatal error: ncurses.h: No such file or directory
compilation terminated.
/home/sub/dpdk-16.07//mk/internal/rte.compile-pre.mk:138: recipe for target 'src/statistics_ncurses.o' failed
make[1]: **\* [src/statistics_ncurses.o] Error 1
/home/sub/dpdk-16.07//mk/rte.extapp.mk:42: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by groud** [comment]
You need to install the ncruses library. if you use Ubuntu you should run:
`sudo apt-get install libncurses-dev`

I sould add this to the requirements...

**Comment by groud** [comment]
`libncurses-dev` is now added to the README file
